name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Altere para 'master' se o seu repositório usar o nome antigo

# Permissões necessárias para interagir com o GitHub Pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/charts/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Instalar Dependências
        run: pnpm install 

      - name: Construir o Projeto (Build)
        run: pnpm run build

      - name: Deploy para o GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages # Branch que o GitHub Actions criará para salvar os arquivos estáticos